baseurl: "/margusmartsepp"
url: "https://margusmartsepp.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LeetCodeC#.md
  - ProjectEulerJava.md
  - AlgorithmsJava.md

title: Type on Strap                                    # site's title
description: "A website with blog posts and pages"      # used by search engines

remote_theme: sylhare/Type-on-Strap 