plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LeetCodeC#.md
  - ProjectEulerJava.md
  - AlgorithmsJava.md
remote_theme: TaylanTatli/Moon