baseurl: "/margusmartsepp"
url: "https://margusmartsepp.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LeetCodeC#.md
  - ProjectEulerJava.md
  - AlgorithmsJava.md

theme: jekyll-theme-time-machine
#For custom themes
#https://github.com/topics/jekyll-theme?o=desc&s=stars
#remote_theme: "mmistakes/jekyll-theme-skinny-bones"